# These are supported funding model platforms

github: "0x4f53"
patreon: "0x4f"
open_collective: # Replace with a single Open Collective username
ko_fi: "o_0x4f"
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: "0x4f53"
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: "https://www.paypal.me/0x4f"
